[phases.copy]
cmds = [
  'mkdir -p /workspace',
  'cp -r . /workspace'
]

[phases.setup]
dependsOn = ['copy']
workingDirectory = '/workspace'
nixPkgs = ['...', 'jq']

[phases.caddy]
dependsOn = ['setup']
nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
nixPkgs = ['caddy']

[phases.fmt]
dependsOn = ['caddy']
workingDirectory = '/workspace'
cmds = ['caddy fmt --overwrite Caddyfile']

[start]
cmd = 'cd /workspace && export ANGULAR_OUTPUT_PATH=$(jq -r "[.projects[] | .architect.build.options.outputPath][0]" angular.json) && exec caddy run --config Caddyfile --adapter caddyfile 2>&1'
